### ISSUE TITLE
Unable to send user/password credentials to the broker?

### ISSUE THREAD

**Issue by nat1craft** [rpdswtk/vsmqtt#1]
Unless I completely missed  it, there seems to be no way to  send username and password to the MQTT broker.

**Comment by rpdswtk** [comment]
That's right. I'm planning to add support for secure connection in the near future

**Comment by khaefner** [comment]
+1 for this!

**Comment by rpdswtk** [comment]
New version is published now with user/password options.
Example config:
```json
{
    "name": "client with password",
    "host": "localhost",
    "port": 1884,
    "username": "user01",
    "password": "securepassword"
}
```
