### ISSUE TITLE
subscribe topic wildcards not supported

### ISSUE THREAD

**Issue by malik1988** [rpdswtk/vsmqtt#103]
with rpdswtk.vsmqtt v1.3.2 on VSCode , subscribe topic wildcards not supported. 

![image](https://user-images.githubusercontent.com/22439325/132166488-60a6caca-b26b-4ffe-926c-09319792ae14.png)

**Comment by rpdswtk** [comment]
Thanks for the feedback. This is fixed now with version 1.3.3.
