### ISSUE TITLE
Ignore not matching server domain in a certificate

### ISSUE THREAD

**Issue by lejsekt** [rpdswtk/vsmqtt#146]
Hi,
thanks for a great extension!

Is there an option to ignore mismatch in the server hostname and the CN in the certificate? Something like --insecure option in mosquitto_pub command.

**Comment by DocMoebiuz** [comment]
this is an option in the underlying TLS connection library but it is not exposed. It is fairly easy to be added.

**Comment by rpdswtk** [comment]
This is now released you can enable it with insecure property in options
