### ISSUE TITLE
Screen goes blank when hitting Subscribe

### ISSUE THREAD

**Issue by joostn** [rpdswtk/vsmqtt#15]
Hi,

Thanks for this extension! It used to work, but since today the window goes blank when hitting Subscribe.

I am connected succesfully to the mqtt server and I can publish topics.
Under 'Subscribe' I enter 'test' and click the Subscribe button. Now the entire VSMQTT window becomes black.

VSCode debugging tools show this error:

Uncaught TypeError: Cannot read property '1' of null
    at vscode-webview://319ac618-e13c-4735-b915-19c41c7167be/host.js:1
(anonymous) @ vscode-webview://319ac618-e13c-4735-b915-19c41c7167be/host.js:1

I've tried on two different computers, mac and windows.
VS code 1.56.2

Any help appreciated!

**Comment by rpdswtk** [comment]
Hi,

Thanks for the feedback. 
I managed to recreate the error. It seems the issue is related to the new vscode release.
You can revert back to 1.55 until I release a fix, I'll try to fix this asap.

**Comment by joostn** [comment]
Thank you!

**Comment by rpdswtk** [comment]
I published the new version (1.2.2) to the marketplace.

**Comment by joostn** [comment]
Great, it works! Thanks!
