### ISSUE TITLE
Prompt for password

### ISSUE THREAD

**Issue by mateuszdrab** [rpdswtk/vsmqtt#192]
Hey, 

Thanks for this extension, it's really handy.

I was wondering if you could add an option to prompt for the username/password on connection. I was thinking perhaps a prompt for credentials setting would do.

This is so that I can actually commit the config in source control, without checking in the creds.

Thanks

**Comment by rpdswtk** [comment]
Hi,

Thanks for the feedback, this is a great idea. I'll implement this soon.

**Comment by rpdswtk** [comment]
This now included in version 1.4.5

**Comment by mateuszdrab** [comment]
> This now included in version 1.4.5

Thank you, will check it out ☺️
