### ISSUE TITLE
Is it still available in VS code marketplace ?

### ISSUE THREAD

**Issue by harvey56** [rpdswtk/vsmqtt#225]
I looked for your extension with `ext install rpdswtk.vsmqtt`. It doesn't exist. I use VSCodium BTW, if that makes a difference.

**Comment by rpdswtk** [comment]
It does make a difference. VSCodium uses a different repository for the extensions.
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by harvey56** [comment]
That's what I suspected.

> You have the following options to obtain such missing extensions:
> 
>     Ask the extension maintainers to publish to [open-vsx.org](https://open-vsx.org/) in addition to the VS Code Marketplace. The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

So, do you think you can publish the extension to open-vsx ? :)

Meanwhile, I will go ahead with the 2 suggestion from the link

**Comment by harvey56** [comment]
UPDATE : [https://github.com/open-vsx/publish-extensions](https://github.com/open-vsx/publish-extensions )

> The first step we recommend is to open an issue with the extension owner. 
> 
> In the long-run it is better for extension owners to publish their own plugins because: Any future issues (features/bugs) with any published extensions in Open VSX will be directed to their original repo/source-control

Can you please add your extension to that market place ? I'd like to use it :)

**Comment by rpdswtk** [comment]
Sure. Unfortunately I can't login to open-vsx.org (https://github.com/eclipse/openvsx/issues/540), but will publish it once it is solved.
