### ISSUE TITLE
Suggestion: ability to clear topic

### ISSUE THREAD

**Issue by mschwartz** [rpdswtk/vsmqtt#244]
Sometimes my code has a bug and stores a useless retained topic/message.  It's a royal pain to remove it - you have to send a null packet to the topic to remove it from the retained backing store.

Ideally, this tool would have a delete (X) button next to the topic/messages in the list to send one of those packets.  

vsmqtt is really good at finding these among a stream of useful topic/messages...

Thanks for this!

**Comment by rpdswtk** [comment]
Thank you for the suggestion. I'll add this feature

**Comment by mschwartz** [comment]
👍

**Comment by rpdswtk** [comment]
Hi, sorry for the long wait. This is included in v1.5.0.
![image](https://github.com/rpdswtk/vsmqtt/assets/31532753/9e4d96ea-90f8-4efb-bfed-4b49077e11fe)
