### ISSUE TITLE
Support for { "rejectUnauthorized": false } in mqtt connection options

### ISSUE THREAD

**Issue by devantler** [rpdswtk/vsmqtt#285]
When trying to debug MQTT over TLS endpoint, I get an `Error: unable to verify the first certificate` (See https://github.com/mqttjs/MQTT.js/issues/271#issuecomment-95045738 for more info.). 

I do not believe the extension currently supports skipping the innate cert validation. Would it be possible to add a configuration parameter that allows us to set `rejectUnauthorized` to `false`?

**Comment by rpdswtk** [comment]
This is now released with 1.4.9

**Comment by devantler** [comment]
Awesome! Thanks a bunch!
