### ISSUE TITLE
ca certificate property

### ISSUE THREAD

**Issue by khaefner** [rpdswtk/vsmqtt#3]
Awesome work on the TLS connections, I tried a couple (mosquitto public and HiveMQ).  Works great!

Not sure if it is possible, but a property option to put the pem string in the setting.json file would be really handy.  The capath can be different on different OSes, and if the cert could be in the settings it would make switching/syncing OSes easy.

Thanks, 

Kyle

**Comment by rpdswtk** [comment]
Thanks for the suggestion. I'll take a look at it.

**Comment by rpdswtk** [comment]
New version is out now. Ca property can be overwritten with PEM format string.
